FROM python:3.13-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml .
COPY app/ app/
COPY alembic.ini .
COPY alembic/ alembic/
COPY entrypoint.sh .
RUN uv pip install --system .

EXPOSE 8000

ENTRYPOINT ["./entrypoint.sh"]
